TRAIN:
  train_batch_size: 32
  lr: 0.0003
  valid_batch_size: 8
  image_size: [224,224]
  min_epochs: 20
  max_epochs: 200
  patience: 30
  device: 1
  model_save_path: ./save_model
  model_save_filename: medseg

MODEL:
  bert_type: microsoft/BiomedVLP-CXR-BERT-specialized
  vision_type: facebook/convnext-tiny-224
  project_dim: 768

# QaTa-COV19
DATA:
  train_csv_path: ./data/QaTa-COV19-v2/prompt/train.csv
  train_root_path: ./data/QaTa-COV19-v2/Train

  val_csv_path: ./data/QaTa-COV19-v2/prompt/train.csv
  val_root_path: ./data/QaTa-COV19-v2/Val

  test_csv_path: ./data/QaTa-COV19-v2/prompt/test.csv
  test_root_path: ./data/QaTa-COV19-v2/Test

#MosMedData+
# DATA:
#   train_csv_path: ./data/MosMedData/prompt/Train_text_MosMedData.csv
#   train_root_path: ./data/MosMedData/Train

#   val_csv_path: ./data/MosMedData/prompt/Val_text_MosMedData.csv
#   val_root_path: ./data/MosMedData/Val

#   test_csv_path: ./data/MosMedData/prompt/Test_text_MosMedData.csv
#   test_root_path: ./data/MosMedData/Test
